// <auto-generated />
namespace BaukCMS.DataLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Sites : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sites));
        
        string IMigrationMetadata.Id
        {
            get { return "201504271823540_Sites"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
